# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
    - bash: echo build firstjob
    - bash: echo $(NewVar)
  - job: SecondJob
    steps:
    - bash: echo build secondjob
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs: 
#   - job: DevDeployJob
#     steps:
#     - bash: echo build $(environment) firstjob
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs: 
#   - job: QADeployJob
#     steps:
#     - bash: echo build $(environment) firstjob
# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs: 
#   - job: ProdDeployJob
#     steps:
#     - bash: echo build $(environment) firstjob